apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp  
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: server
        image: 172.23.161.55:5000/webapp-test:latest 
        ports:
        - containerPort: 8080