apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      - name: cloudflare-tunnel
        image: cloudflare/cloudflared:latest
        command: [
          "cloudflared", "tunnel", "--no-tls-verify", "--url", "http://10.152.183.124:8080", "token", "${CLOUDFLARE_API_KEY}"
          ]
        # env:
        # - name: CF_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudflare-token
        #       key: token
        env:
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: CLOUDFLARE_API_KEY
        volumeMounts:
        - name: cloudflare-api-key
          mountPath: /etc/cloudflare/api-key
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: cloudflare-api-key
          secret:
            secretName: cloudflare-api-key