apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      - name: cloudflare-tunnel
        image: cloudflare/cloudflared:latest
        - command:
          - cloudflared
          - tunnel
          # In a k8s environment, the metrics server needs to listen outside the pod it runs on. 
          # The address 0.0.0.0:2000 allows any pod in the namespace.
          - run
          args:
          - --token
          - "${CLOUDFLARE_TOKEN}"
        # env:
        # - name: CF_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudflare-token
        #       key: token
        env:
        - name: CLOUDFLARE_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: CLOUDFLARE_TOKEN