apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      - name: cloudflare-tunnel
        image: cloudflare/cloudflared:latest
        command: [
          "sudo sysctl", "-w", "net.core.rmem_max=7500000;", 
          "sudo sysctl", "-w", "net.core.wmem_max=7500000;",
          "cloudflared", "tunnel", "--url", "http://10.152.183.124:8080", "my-tunnel"
          ]
        # env:
        # - name: CF_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudflare-token
        #       key: token
      volumes:
        - name: config-volume
          emptyDir: {}