apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-tunnel
  template:
    metadata:
      labels:
        app: cloudflare-tunnel
    spec:
      containers:
      # - command: [
      #   "cloudflared", "tunnel", "--no-autoupdate=true", "run", "--token", "$TUNNEL_TOKEN"
      # ]
      - name: cloudflare-tunnel
        image: cloudflare/cloudflared:latest
        # env:
        # - name: CF_API_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudflare-token
        #       key: token
        command: [ "/bin/bash", "-c", "--", "while", "true;"," "do", "sleep", "30;"," "done;"]
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: TUNNEL_TOKEN