apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
provisioner: kubernetes.io/no-provisioner
storageClassName: local-hostpath
accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 15Gi